-----

In [1]:
from hsic.hsic_utils import (get_K_U_sobolev_looped as ku_loop, get_K_U_sobolev_vectorized as ku_vect)
import numpy as np
n = 3
card_u = 2
a = np.random.uniform(0,1,size=(n,card_u))
a

/opt/anaconda3/envs/set_kbsa/lib/python3.10/site-packages/ufl/__init__.py:250: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


array([[0.54113729, 0.73257084],
       [0.66293395, 0.71872831],
       [0.01580029, 0.98947096]])

In [8]:
np.random.choice([0,1], size=(2,3))

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
ku_loop(n=n, num_of_inputs=card_u, input_data=a, which_input_one_hot='01')

array([[1.15097135, 0.87143851, 0.92144573],
       [0.87143851, 1.21543048, 1.05751556],
       [0.92144573, 1.05751556, 1.10752278]])

In [15]:
ku_vect(n=n, num_of_inputs=card_u, input_data=a, which_input_one_hot='01')

array([[1.15097135, 0.87143851, 0.92144573],
       [0.87143851, 1.21543048, 1.05751556],
       [0.92144573, 1.05751556, 1.10752278]])

In [52]:
domain = np.array(([[-5,-3],[10,20],[10,20],[10,20]]))
print(domain.shape[0])
m=1
np.random.uniform(domain[:,0], domain[:,1], size=(m, domain.shape[0]))

4


array([[-4.71827842, 16.68553514, 15.39440171, 17.27335501]])

In [17]:
from numeric_models.analytic_models import fellmann_function as f
x_domain = [-5,5]
x_1 = 3
m = 20
x_vals = np.linspace(x_domain[0], x_domain[1], m)
u_1 = -4
u_2 = 3
results = []
for x in x_vals:
    results.append(f(u_1=u_1, u_2=u_2, x_1=x_1, x_2=x))
results

[-22.0,
 -19.36842105263158,
 -16.736842105263158,
 -14.105263157894736,
 -11.473684210526315,
 -8.842105263157897,
 -6.210526315789473,
 -3.578947368421053,
 -0.9473684210526336,
 1.6842105263157876,
 4.315789473684208,
 6.947368421052628,
 9.578947368421053,
 12.210526315789473,
 14.842105263157894,
 17.473684210526315,
 20.105263157894733,
 22.736842105263158,
 25.368421052631575,
 28.0]

In [7]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a@b

np.int64(32)

In [4]:
import numpy as np
def _fixed_uniform(low, high, size):
        low = np.asarray(low)
        high = np.asarray(high)
        linspaces_grid = [np.linspace(low[j], high[j], size[0]) for j in range(size[1])]
        return np.column_stack(linspaces_grid)
low = [0,1,2]
high = [1,2,3]
size = [10,3]
_fixed_uniform(low, high, size)

array([[0.        , 1.        , 2.        ],
       [0.11111111, 1.11111111, 2.11111111],
       [0.22222222, 1.22222222, 2.22222222],
       [0.33333333, 1.33333333, 2.33333333],
       [0.44444444, 1.44444444, 2.44444444],
       [0.55555556, 1.55555556, 2.55555556],
       [0.66666667, 1.66666667, 2.66666667],
       [0.77777778, 1.77777778, 2.77777778],
       [0.88888889, 1.88888889, 2.88888889],
       [1.        , 2.        , 3.        ]])

In [3]:

"""
NOTEE-> THIS MUST GO INTO THE TESTCASES!!!
"""
from hsic.hsic_utils import get_input_data_from_file_analytical, get_process_model_output_data_analytical
from hsic.hsic import hsic
from numeric_models.analytic_models import (fellmann_function_generator as gen_fellmann,
                                            ishigami_vectorized_generator as gen_ishigami,
                                            affine_linear_generator as gen_afflin)
import numpy as np
from fenics import MPI 
from numeric_models.numeric_models_utils import generate_data_multi_dim
process_settings={'fellmann': {'data_directory': 'data/experiment_data/fellmann',
                                        'process_generator': gen_fellmann,
                                        'u_domain_specifications': [{'distribution_type': 'uniform', 'min': -5, 'max': 5},
                                                                    {'distribution_type': 'uniform', 'min': -5, 'max': 5}],
                                        'u_one_hot_key_map': {'10': 'U_1', '01': 'U_2'},
                                        'test_domain': np.array([[-5,5],[-5,5]]),
                                        'g_constraint': 0}, 

                'ishigami': {'data_directory': 'data/experiment_data/ishigami',
                            'process_generator': gen_ishigami,
                            'u_domain_specifications': [{'distribution_type': 'uniform', 'min': -np.pi, 'max': np.pi},
                                                        {'distribution_type': 'uniform', 'min': -np.pi, 'max': np.pi}],
                            'u_one_hot_key_map': {'10': 'U_1', '01': 'U_2'},
                            'test_domain': np.array([[-np.pi,np.pi]]),
                            'g_constraint': 0},
                            
                'affine_linear': {'data_directory': 'data/experiment_data/affine_linear',
                            'process_generator': gen_afflin,
                            'u_domain_specifications': [{'distribution_type': 'uniform', 'min': 0, 'max': 1},
                                                        {'distribution_type': 'uniform', 'min': 0, 'max': 1},
                                                        {'distribution_type': 'uniform', 'min': 0, 'max': 1}],
                            'u_one_hot_key_map': {'100': 'U_1', '010': 'U_2', '001': 'U_3'},
                            'test_domain': np.array([[0.25,0.75]]),
                            'g_constraint': 3.75}} #5.25

n_list = [5000]
process_name = 'fellmann'
g_constraint = process_settings[process_name]['g_constraint']
for _ in range(1):
    for n in n_list:
        m = n*3
        # u_arr = generate_data_multi_dim(domain_specification=process_settings[process_name]['u_domain_specifications'], 
        #                                 num_of_samples_n=n)
        num_of_u_inputs = len(process_settings[process_name]['u_domain_specifications'])
        u_arr = get_input_data_from_file_analytical(data_directory=process_settings[process_name]['data_directory'],
                                                    num_of_u_inputs=num_of_u_inputs,
                                                    n=n)
        binary_system_output_data = get_process_model_output_data_analytical(u_arr=u_arr,
                                                                            process_generator=process_settings[process_name]['process_generator'],
                                                                            test_domain=process_settings[process_name]['test_domain'],
                                                                            num_of_spatial_sampling_m=m,
                                                                            g_constraint=g_constraint,
                                                                            rng=np.random.uniform,
                                                                            fix_x_vect=False)
        # x_vals = np.linspace(test_domain[0][0], test_domain[0][1], m)
        # x_2 = 2.0
        # binary_system_output_data = np.zeros((n, m), dtype=np.uint8)
        # for i in range(n):
        #     f = gen_fellmann(u_arr[i])
        #     for j in range(m):
        #         x = np.array([x_vals[j], x_2])
        #         binary_system_output_data[i,j] = (f(x)<=g_constraint)
        # computed_1 = hsic(u_domain_specifications=process_settings[process_name]['u_domain_specifications'],
        #                 u_one_hot_key_map=process_settings[process_name]['u_one_hot_key_map'],
        #                 binary_system_output_data=binary_system_output_data,
        #                 u_arr=u_arr,
        #                 vectorized_hsic_flag=False,
        #                 vectorized_K_U_flag=True)
        # print(f"n: {n}")
        # # print("hsic_looped")
        # # print(computed_1)
        computed_2 = hsic(u_domain_specifications=process_settings[process_name]['u_domain_specifications'],
                        u_one_hot_key_map=process_settings[process_name]['u_one_hot_key_map'],
                        binary_system_output_data=binary_system_output_data,
                        u_arr=u_arr,
                        vectorized_hsic_flag=True,
                        vectorized_K_U_flag=True)
        print("hsic_vect")
        print(computed_2)
        # computed_3 = hsic(data_directory=data_directory,
        #                 u_domain_specifications=u_domain_specifications_fellmann,
        #                 u_one_hot_key_map=u_one_hot_key_map,
        #                 g_constraint=g_constraint,
        #                 binary_system_output_data=binary_system_output_data,
        #                 u_arr=u_arr,
        #                 vectorized_hsic_flag=True,
        #                 vectorized_K_U_flag=False)
        # print(computed_3)
        # computed_4 = hsic(u_domain_specifications=process_settings[process_name]['u_domain_specifications'],
        #                 u_one_hot_key_map=process_settings[process_name]['u_one_hot_key_map'],
        #                 binary_system_output_data=binary_system_output_data,
        #                 u_arr=u_arr,
        #                 vectorized_hsic_flag=True,
        #                 vectorized_K_U_flag=True,
        #                 hsic_control_method_flag=True)
        # print(computed_4)
        # print('hsic_direct_trace')
        print('\n')

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0
Using 5000 data points.
Wall-clock time of get_K_U_sobolev_vectorized with chunks of 1024: 0.264 (s)
Wall-clock time of get_K_U_sobolev_vectorized with chunks of 1024: 0.256 (s)
Wall-clock time of get_K_U_sobolev_vectorized with chunks of 1024: 0.463 (s)
Wall-clock time of dt__get_gram_matrix: 3.049 (s)
Wall-clock time of calculate_hsic_vectorized: 0.266 (s)
Wall-clock time of calculate_hsic_vectorized: 0.264 (s)
Wall-clock time of calculate_hsic_vectorized: 0.291 (s)
hsic_vect
{'U_1': np.float64(0.39437305662232724), 'U_2': np.float64(0.6067370533832601)}




In [9]:
import numpy as np
process_settings={'2d_cdr': {'data_directory': 'data/experiment_data/cdr/hsic',
                                'fem_mesh_directory': 'data/CDR/mesh_save_dir/rectangle.xdmf',
                                'u_domain_specifications': [{'distribution_type': 'log_uniform', 'min': 5.5e11, 'max': 1.5e12},
                                                            {'distribution_type': 'log_uniform', 'min': 1.5e3, 'max': 9.5e3},
                                                            {'distribution_type': 'uniform', 'min': 850, 'max': 1000},
                                                            {'distribution_type': 'uniform', 'min': 200, 'max': 400},
                                                            {'distribution_type': 'uniform', 'min': 0.5, 'max': 1.5}],
                                'u_one_hot_key_map': {'10000': 'A', '01000': 'E', '00100': 'T_i', '00010': 'T_o', '00001': 'phi'},
                                'test_domain': np.array([[0.5, 0.15],[0.2, 0.3]]),
                                'g_constraint': 700,
                                'field_of_interest': 'a'}}
print(f"{process_settings['2d_cdr']['data_directory']}")

data/experiment_data/cdr/hsic


In [6]:
from numpy.typing import NDArray
import numpy as np
a = np.ones((10,2))
print(a)
type(a)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


numpy.ndarray

In [2]:
import numpy as np
m=3
test_domain=process_settings[process_name]['test_domain']
x_vect = np.random.uniform(low=test_domain[:, 0], high=test_domain[:, 1], size=(m, test_domain.shape[0]))
print(x_vect)
print(x_vect.shape)
f_samplings = np.zeros(m)

[[ 2.12171112 -2.26102307]
 [-2.67788361 -1.92831353]
 [-4.07717137 -4.10568176]]
(3, 2)


In [3]:
x_vect[0]

array([ 2.12171112, -2.26102307])

In [5]:
def ff(x, u_1, u_2):
    if x.ndim == 1:
        return -x[0]*x[0]+5*x[1]-u_1+u_2*u_2-1
    else:
        x_1 = x[:,0]
        x_2 = x[:,1]
        return -x_1*x_1+5*x_2-u_1+u_2*u_2-1
for x in x_vect:
    print(ff(x=x,u_1=1,u_2=1))

-16.806773423459454
-17.81262830392336
-38.1517352035482


In [8]:
f = gen_fellmann(u=[1,1])
f(x_vect).shape

[ 2.12171112 -2.67788361 -4.07717137]
[-2.26102307 -1.92831353 -4.10568176]


(3,)

In [30]:
x=np.random.uniform(0,1,size=(5,1))
print(x)
f(x)

[[0.47132678]
 [0.8388022 ]
 [0.58352104]
 [0.43363704]
 [0.05580866]]


array([[10.23566339],
       [10.4194011 ],
       [10.29176052],
       [10.21681852],
       [10.02790433]])

In [2]:
import numpy as np
2**int(np.floor(np.log2(10000))-1)

4096

In [2]:
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/envs/set_kbsa/include
    lib directory: /opt/anaconda3/envs/set_kbsa/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /opt/anaconda3/envs/set_kbsa/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/envs/set_kbsa/include
    lib directory: /opt/anaconda3/envs/set_kbsa/lib
    name: lapack
    openblas configuration: unknown
    pc file directory: /opt/anaconda3/envs/set_kbsa/lib/pkgconfig
    version: 3.9.0
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/envs/set_kbsa/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/numpy_1721965842171/work=/usr/local/src/conda/numpy-2.0.1,
      -fdebug-prefix-map=/opt/anaconda3/envs/set_kbsa=/usr/local/src/conda-prefix,
      -D_FORTIFY_SOURCE=2, -i

In [2]:
from hsic.hsic import hsic
from numpy import array, pi as np_pi
from numeric_models.analytic_models import (ishigami_vectorized_generator as gen_ishigami, fellmann_function_generator as gen_fellmann)
n = 2000
m = 2000
test_domain = array([[-5,5],[-5,5]])
# u_domain_specifications_ishigami = [{'distribution_type': 'uniform', 'min': -np_pi, 'max': np_pi},
#                         {'distribution_type': 'uniform', 'min': -np_pi, 'max': np_pi}]
u_one_hot_key_map = {'10': 'U_1', '01': 'U_2'}
g_constraint = 0

results = []
for _ in range(1):
    curr_result = hsic(data_directory=data_dir,
                        num_of_spatial_sampling_m=m,
                        n=n,
                        test_domain=test_domain,
                        u_domain_specifications=u_domain_specifications_fellmann,
                        u_one_hot_key_map=u_one_hot_key_map,
                        g_constraint=g_constraint,
                        process_type='analytical',
                        analytical_process_settings={'process_generator': gen_fellmann},
                        vectorized_hsic_flag=True,
                        vectorized_K_U_flag=True)
    results.append(curr_result)
    print(curr_result, '\n')
    curr_result = hsic(data_directory=data_dir,
                        num_of_spatial_sampling_m=m,
                        n=n,
                        test_domain=test_domain,
                        u_domain_specifications=u_domain_specifications_fellmann,
                        u_one_hot_key_map=u_one_hot_key_map,
                        g_constraint=g_constraint,
                        process_type='analytical',
                        analytical_process_settings={'process_generator': gen_fellmann},
                        vectorized_hsic_flag=True,
                        vectorized_K_U_flag=True,
                        hsic_control_method_flag=True)
    results.append(curr_result)
    print(curr_result, '\n')

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0
Using 2000 data points.
Wall-clock time of calculate_hsic_vectorized: 0.039 (s)
Wall-clock time of calculate_hsic_vectorized: 0.031 (s)
Wall-clock time of calculate_hsic_vectorized: 0.032 (s)
{'U_1': np.float64(-0.3206152855038593), 'U_2': np.float64(1.3547345772527655)} 

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0
Using 2000 data points.
Wall-clock time of calculate_hsic_method_2: 0.183 (s)
Wall-clock time of calculate_hsic_method_2: 0.228 (s)
Wall-clock time of calculate_hsic_method_2: 0.280 (s)
{'U_1': np.float64(-0.3783194473299413), 'U_2': np.float64(1.412845656306073)} 



In [ ]:
from numeric_models.analytic_models import ishigami_vectorized_generator as gen_ishigami
import numpy as np
f = gen_ishigami(u_1=1, u_2=1)

In [2]:
from types import FunctionType
from numba.core.registry import CPUDispatcher
from typing import Union
def ff(a,b):
    def innf(x):
        return a+b+x
    return innf
def fenfen(fen: Union[FunctionType, CPUDispatcher]):
    return fen

myf = ff(1,2)
myff = fenfen(myf)
print(myff(3))
type(myff) == FunctionType

6


True

In [ ]:
from hsic.hsic_utils import get_data_file_dirs
from numpy import (array as np_array, sum as np_sum, zeros as np_zeros, load as np_load)
n = 999999
input_data_dirs_list_to_use, n_max_list = get_data_file_dirs(base_dir='data/experiment_data/ishigami', data_type='input_data', process_type='analytical', return_n_max_list=True)
n_max = np_sum(np_array(n_max_list))
if type(n) != int:
    n = int(n)
if n > n_max:
    n = n_max
if n < 1:   
    n=1
u_arr = np_zeros((n, 2))
u_total_counter = 0
for i, dir in enumerate(input_data_dirs_list_to_use):
    if u_total_counter == n:
        continue
    u_arr_curr = np_load(dir)
    left_to_add_counts = n - u_total_counter

    if left_to_add_counts >= len(u_arr_curr):
        u_arr[u_total_counter:(u_total_counter+len(u_arr_curr))] = u_arr_curr
        u_total_counter += len(u_arr_curr)
    else:
        u_arr[u_total_counter:(u_total_counter+left_to_add_counts)] = u_arr_curr[:left_to_add_counts]
        u_total_counter += left_to_add_counts
print(u_total_counter)  

# print(u_arr.shape)
# left_to_add_counts


Num_of_parent_skips: 0
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0
100000


In [ ]:
import numpy as np
int(np.floor(1000 / 3))

333

In [30]:
from data_generation_scripts.analytical_models import analytical_models_experiment as ame

u_domain_specs = [{'distribution_type': 'uniform', 'min': -5, 'max': 5},
                {'distribution_type': 'uniform', 'min': -5, 'max': 5}]
ame(u_domain_specs=u_domain_specs, 
    num_of_experiments=1000000,
    parent_directory='data/experiment_data')

In [10]:
A = ['a', 'b', 'c']
for i, s in enumerate(A):
    print(f"{i}: {s}")

0: a
1: b
2: c


In [5]:
for _ in range(10000000):
    x = np.random.uniform(-5,5)
    f(x)

##### Simulation time estimation

In [1]:
t_per_itr = 46.215293/1000
print(f"time per iter: {t_per_itr:0.3} s")
N = 1000
total_time_steps = 500
total_simulation_time = N * total_time_steps * t_per_itr
print(f"Total simulation time per node: {total_simulation_time/3600:0.4} hours")
num_of_nodes = 12
print(f"Total simulation time on {num_of_nodes} nodes: {total_simulation_time/(3600*num_of_nodes):0.4} hours")

time per iter: 0.0462 s
Total simulation time per node: 6.419 hours
Total simulation time on 12 nodes: 0.5349 hours


Simulation data storage requirement estimation

In [ ]:
data_req_per_sampling_est_bytes = 1706345  #bytes
#1 GiB = 1024**3 B
data_req_per_sampling_est_GiB = 0.0015891576185822 #GiB
total_data_storage_req_est = 6*N*data_req_per_sampling_est_GiB
print(f"Total data storage requirement: {total_data_storage_req_est:0.4} GB")

Total data storage requirement: 47.67 GB


-----

In [6]:
import numpy as np
bitstr='00010'
bitstr_bool = np.array([c == '1' for c in bitstr], dtype=bool)
np.where(bitstr_bool)[0]

array([3])

In [ ]:
u_A = gen_log_uniform(a=5.5e11, b=1.5e12, size=6)
u_E = gen_log_uniform(a=1.5e3, b=9.5e3, size=6)
u_T_i = gen_uniform(a=200, b=400,size=6)
u_T_o = gen_uniform(a=850, b=1000,size=6)
u_phi = gen_uniform(a=0.5, b=1.5,size=6)
u_input = np_arr([u_A, u_E, u_T_i, u_T_o, u_phi])
print(u_input[:,0])
np_save(file="to_save.npy", arr=u_input[:,0])

[8.14550529e+11 2.48418238e+03 3.49455307e+02 9.75168659e+02
 7.18757882e-01]


In [18]:
from kbsa.kbsa_main import run_kbsa, get_kbsa_datafile_name
import numpy as np
from utils import numeric_models as nm
from utils import plotter
from dolfin import Point
from kbsa.model_generators import get_CDR

In [96]:
import time
time.time()

1763486338.170223

In [32]:
def gen_log_uniform(a, b, size=None):
    u = np.random.uniform(np.log(a), np.log(b), size=size)
    return np.exp(u)

def gen_uniform(a, b, size=None):
    return np.random.uniform(a, b, size=size)

def transform_logUnif_to_unitUnif(a, b, log_unif_samples):
    transformed_samples = (np.log(log_unif_samples) - np.log(a))/(np.log(b)-np.log(a))
    assert np.sum((transformed_samples>1)) + np.sum((transformed_samples<0))==0
    return transformed_samples

def transform_unif_to_unifUnif(a, b, unif_samples):
    transformed_samples = (unif_samples-a)/(b-a)
    assert np.sum((transformed_samples>1)) + np.sum((transformed_samples<0))==0
    return transformed_samples
# NOTE: NEED TO SAVE THESE GENERATED SAMPLES TO A FILE.
# N = 1
# A = gen_log_uniform(a=5.5e11, b=1.5e12, size=(6, N))
# E = gen_log_uniform(a=1.5e3, b=9.5e3, size=(6, N))
# T_i = gen_uniform(a=200, b=400,size=(6, N))
# T_o = gen_uniform(a=850, b=1000,size=(6, N))
# phi = gen_uniform(a=0.5, b=1.5,size=(6, N))
# print(A)
# print(E)
# print(T_i)
# print(T_o)
# print(phi)
# u_input = np.array([A, E, T_i, T_o, phi])
# u_input.shape
a = np.random.uniform(0,5)
b = np.random.uniform(6,10)

log_unif_samples = gen_log_uniform(a=a, b=b, size=(10, 5))
print(log_unif_samples)
print(transform_logUnif_to_unitUnif(a=a,b=b,log_unif_samples=log_unif_samples))

# unif_samples = gen_uniform(a=a,b=b,size=10)
# transform_unif_to_unifUnif(a=a,b=b,unif_samples=unif_samples)

# from scipy import stats
# logUnifs = stats.loguniform.rvs(a,b, size=100000)

[[4.23813545 5.01271692 5.79162368 4.29317342 3.72207438]
 [2.59612231 5.88125241 5.90943547 3.6115932  5.14456759]
 [6.29022107 4.02434742 6.32352187 3.46899466 5.91806832]
 [3.03591334 3.70313878 6.15051597 3.9369428  2.66795585]
 [5.66194279 3.96510534 5.53863259 5.16797521 3.41298837]
 [2.92357836 4.93381774 2.61817257 4.4903297  6.55061284]
 [3.57102221 2.49187862 5.30936795 5.92497493 6.69790549]
 [2.7363036  4.00060645 4.37945636 4.76641713 3.1431761 ]
 [3.63764305 6.07209772 4.49151138 3.56935176 2.89775799]
 [2.42362455 5.26444094 2.62534323 3.26261728 3.36040091]]
[[0.54382605 0.70204285 0.83818434 0.55598797 0.42143904]
 [0.08186228 0.85265963 0.85716571 0.39303702 0.72651535]
 [0.91602611 0.49503738 0.92100304 0.35506587 0.85854168]
 [0.22937017 0.41663153 0.89485549 0.4743399  0.10758881]
 [0.81683901 0.48105856 0.79608388 0.73079434 0.33972387]
 [0.19383107 0.6870888  0.08983433 0.59830986 0.9542595 ]
 [0.38238856 0.04323336 0.75623636 0.85964107 0.975219  ]
 [0.13143178 

In [100]:
for i, s in enumerate(['a', 'b']):
    print(s, i)

a 0
b 1


In [ ]:

def unit_uniform_rng(size, type):
    if type == 'A':
        np
        return np.random.uniform(5.5e11, 1.5e12, size=size)
    return 


def generate_cdr_sample():
    fuel_rng = 
    model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.1, 
                            'num_steps':5, 
                            'return_bool': False,
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}

SyntaxError: incomplete input (119094012.py, line 1)

In [52]:
0.05/100

0.0001*300
0.05/0.0001

500.0

In [4]:
models_list = ['cdr']
kernel_types_list = ['sobolev']
model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.05, 
                            'num_steps': 5, 
                            'return_bool': False,
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}
x_domains_dict = {'cdr': np.array([[0.2,0.3],[0.01,0.2]])}
u_domains_dict = {'cdr': np.array([[5e11,1.5e12],[1.5e3,9.5e3],[850,1000],[200,400],[0.5,1.5]])}

In [ ]:
# from kbsa.utils_kbsa import _get_u_samples_arr_to_kernel, _get_u_samples_arr, _get_u_indexSuperset_oneHot
# u_domain = u_domains_dict['cdr']
# # dim_of_U = len(u_domain)
# dim_of_U=5
# u_indexSuperset_oneHot = _get_u_indexSuperset_oneHot(dim_of_U=dim_of_U, higher_order=False)
# dim_of_u_superset = len(u_indexSuperset_oneHot)
# # f"{u_indexSuperset_oneHot}".replace('[','').replace(']','').replace('\'','').replace('\'','')

In [3]:
n = 1
u_samples_arr_to_kernel = _get_u_samples_arr_to_kernel(dim_of_u_superset=dim_of_u_superset, dim_of_U=dim_of_U, n=n)
u_samples_arr = _get_u_samples_arr(u_samples_arr_to_kernel=u_samples_arr_to_kernel, u_domain=u_domain, dim_of_U=dim_of_U,dim_of_u_superset=dim_of_u_superset, gamma_type='cdr')

NameError: name '_get_u_samples_arr_to_kernel' is not defined

In [3]:
u_test = u_samples_arr[0][0]
u_test

NameError: name 'u_samples_arr' is not defined

In [29]:
0.05 / 100

0.0005

In [4]:
my_fen = get_CDR(params=model_params_dict['cdr'])

In [5]:
result_fens = my_fen(u=u_input[:,0,0])

Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.


In [10]:
x_0 = np.random.uniform(0,1)
x_1 = np.random.uniform(0,0.5)
print(f"{x_0}, {x_1}")

0.019651405462366434, 0.3450282292399109


In [227]:
type(result_fens)

list

In [6]:
from dolfin import File, XDMFFile, Constant, conditional, le, project
from dolfin import Mesh,FunctionSpace,Function

In [7]:
mesh = Mesh()
with XDMFFile("data/CDR/mesh_save_dir/rectangle.xdmf") as xdmf:
    xdmf.read(mesh)

In [8]:
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/fuel_field') as xdmf_1:
    xdmf_1.write_checkpoint(result_fens[0], 'fuel_field', 0, XDMFFile.Encoding.HDF5, append=False)
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/oxygen_field') as xdmf_2:
    xdmf_2.write_checkpoint(result_fens[1], 'oxygen_field', 0, XDMFFile.Encoding.HDF5, append=False)
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/product_field') as xdmf_3:
    xdmf_3.write_checkpoint(result_fens[2], 'product_field', 0, XDMFFile.Encoding.HDF5, append=False)   
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/temp_field') as xdmf_4:
    xdmf_4.write_checkpoint(result_fens[3], 'temp_field', 0, XDMFFile.Encoding.HDF5, append=False)

In [44]:
from datetime import datetime
import time 
print(time.time_ns())
datetime.now().strftime("%Y_%m_%d")

1763319986155429000


'2025_11_16'

In [213]:
for j in range(4):
    print([i for i in range(j, 6, 4)])

[0, 4]
[1, 5]
[2]
[3]


In [163]:
from datetime import datetime
import time, uuid
from os import path, makedirs

save_dir = "data/CDR/experimental_data"

N = 2
parent_uid = str(uuid.uuid4().hex)
folder_name_exprim_parent = "exprim_start_" + datetime.now().strftime("%Y_%m_%d_%H_%M_%S__uid_") + parent_uid
for i in range(N):
    curr_date = datetime.now().strftime("%Y_%m_%d")  
    curr_itr_file_uid = f"{time.time_ns()}_{str(uuid.uuid4().hex)}"
    folder_full_path = f"{save_dir}/{folder_name_exprim_parent}/uid_{curr_itr_file_uid}"
    makedirs(folder_full_path, exist_ok=True)
    with open(f"{folder_full_path}/metadata_uid_{curr_itr_file_uid}.txt", "w") as f:
        f.write(f"parent_uid_{parent_uid};\ncurr_itr_uid_{curr_itr_file_uid};")

    # print(folder_full_path)

# formatted = datetime.now().isoformat(timespec='nanoseconds')
# print(formatted)
# print(uuid)
# 
# folder_name_exprim_parent = "exprim_start" + datetime.now().strftime("%Y_%m_%d__%H_%M_%S")
# curr_itr = 1
# curr_itr_datetime = datetime.now().strftime("%Y_%m_%d__%H_%M_%S")
#  = path.join(dir_to_save, folder_name)
# 
# makedirs(curr_output_dir, exist_ok=True)

In [ ]:
from dolfin import Mesh, FunctionSpace, Function, XDMFFile

mesh = Mesh()
with XDMFFile("data/CDR/mesh_save_dir/rectangle.xdmf") as xdmf:
    xdmf.read(mesh)
    
V_1 = FunctionSpace(mesh, 'CG', 1) 
V_2 = FunctionSpace(mesh, 'CG', 1)
V_3 = FunctionSpace(mesh, 'CG', 1)
V_4 = FunctionSpace(mesh, 'CG', 1)
fuel_field_t_now = Function(V_1)
oxyxen_field_t_now = Function(V_2)
product_field_t_now = Function(V_3)
temp_field_t_now = Function(V_4)

a_load_path = 'data/CDR/state_saves'
sample_load_path = 'data/experiment_data/2025_11_21_16_49_53__f9d9617b0d0d44cdaa5fd061a1734cad/94137314f05046f0a4bdac50a5d03bef/00001'

with XDMFFile(mesh.mpi_comm(), f'{sample_load_path}/fuel_field') as xdmf_1:
    xdmf_1.read_checkpoint(fuel_field_t_now, 'fuel_field', 0)
with XDMFFile(mesh.mpi_comm(), f'{sample_load_path}/oxygen_field') as xdmf_2:
    xdmf_2.read_checkpoint(oxyxen_field_t_now, 'oxygen_field', 0)
with XDMFFile(mesh.mpi_comm(), f'{sample_load_path}/product_field') as xdmf_3:
    xdmf_3.read_checkpoint(product_field_t_now, 'product_field', 0) 
with XDMFFile(mesh.mpi_comm(), f'{sample_load_path}/temp_field') as xdmf_4:
    xdmf_4.read_checkpoint(temp_field_t_now, 'temp_field', 0)

In [44]:
from dolfin import Point
from numpy import random as np_random
x_0 = np_random.uniform(0,1)
x_1 = np_random.uniform(0,0.5)
# x_0 = 0.25
# x_1 = 0.1
print(fuel_field_t_now(Point([x_0, x_1])))
print(oxyxen_field_t_now(Point([x_0, x_1])))
print(product_field_t_now(Point([x_0, x_1])))
print(temp_field_t_now(Point([x_0, x_1])))

0.007937835148330914
0.06364653345486973
0.005361466784768133
789.9353790969775


In [45]:
from numpy import load as np_load
inputs_u = np_load(f"{sample_load_path}/input_data.npy")
inputs_u

array([5.84078611e+11, 6.24035019e+03, 3.85954369e+02, 8.62347811e+02,
       9.79661178e-01])

In [2]:
size = 12
N = 1000
max_jobs = (N + size - 1) // size
print(max_jobs)
num_extra_runs = 0
for rank in range(size):
    adj_print = False
    A = range(rank, N, size)
    job_indices = [i for i in A]
    if len(A) < max_jobs:
        job_indices.append(None)
        adj_print = True
        num_extra_runs += 1
    print('Final job_indices:',job_indices)
print(num_extra_runs)

84
Final job_indices: [0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180, 192, 204, 216, 228, 240, 252, 264, 276, 288, 300, 312, 324, 336, 348, 360, 372, 384, 396, 408, 420, 432, 444, 456, 468, 480, 492, 504, 516, 528, 540, 552, 564, 576, 588, 600, 612, 624, 636, 648, 660, 672, 684, 696, 708, 720, 732, 744, 756, 768, 780, 792, 804, 816, 828, 840, 852, 864, 876, 888, 900, 912, 924, 936, 948, 960, 972, 984, 996]
Final job_indices: [1, 13, 25, 37, 49, 61, 73, 85, 97, 109, 121, 133, 145, 157, 169, 181, 193, 205, 217, 229, 241, 253, 265, 277, 289, 301, 313, 325, 337, 349, 361, 373, 385, 397, 409, 421, 433, 445, 457, 469, 481, 493, 505, 517, 529, 541, 553, 565, 577, 589, 601, 613, 625, 637, 649, 661, 673, 685, 697, 709, 721, 733, 745, 757, 769, 781, 793, 805, 817, 829, 841, 853, 865, 877, 889, 901, 913, 925, 937, 949, 961, 973, 985, 997]
Final job_indices: [2, 14, 26, 38, 50, 62, 74, 86, 98, 110, 122, 134, 146, 158, 170, 182, 194, 206, 218, 230, 242, 254, 266, 278, 290, 30

In [164]:
from scipy import stats
a = np.random.uniform(0.0001,10)
b = np.random.uniform(10,10000)
logUnifs = stats.loguniform.rvs(a,b, size=100000)
np.sum(((np.log(logUnifs) - np.log(a))/(np.log(b)-np.log(a))>1)) + np.sum(((np.log(logUnifs) - np.log(a))/(np.log(b)-np.log(a))<0))

np.int64(0)

In [ ]:
x_0 = np.random.uniform(0,1)
x_1 = np.random.uniform(0,0.5)
[f(Point([x_0, x_1])) for f in result_fens]

In [ ]:
import numpy as np
from utils import numeric_models as nm

In [3]:
cdr_model = nm.model(model_type='cdr', 
                    t_end_cdr=0.05, 
                    num_steps_cdr=50, 
                    output_paraview=False, 
                    mesh_2D_dir='data/CDR/mesh_save_dir/rectangle.xdmf', 
                    mesh_steps=0.025)

In [4]:
cdr_model.output_paraview = True
cdr_model.get_cdr()
# cdr_model.save_curr_cdr_output_to_file()
# plotter.plot(model=cdr_model, plot_type='2D_mesh')

Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.


In [ ]:
models_list = ['cdr']
kernel_types_list = ['sobolev']
model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.1, 
                            'num_steps':10, 
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}
x_domains_dict = {'cdr': np.array([[0.2,0.3],[0.01,0.2]])}
u_domains_dict = {'cdr': np.array([[5e11,1.5e12],[1.5e3,9.5e3],[850,1000],[200,400],[0.5,1.5]])}
num_of_trials = 20
# num_of_trials = 5
n_list = [500]
# n_list = [50]
hsic_types_dict = {'unbiased': False, 'biased': False, 'R2': False, 'fellman': True}


In [ ]:
for n_list in N_list_list:
        file_name = get_kbsa_datafile_name(models_list=models_list, 
                                x_domains_dict=x_domains_dict, 
                                kernel_types_list=kernel_types_list, 
                                hsic_types_dict=hsic_types_dict, 
                                n_list=n_list, 
                                num_of_trials=num_of_trials,
                                model_params_dict=model_params_dict)

        data = run_kbsa(hsic_types_dict=hsic_types_dict,
                        kernel_types_list=kernel_types_list,
                        models_list=models_list,
                        model_params_dict=model_params_dict,
                        x_domains_dict=x_domains_dict,
                        sample_x_from_mesh=True,
                        u_domains_dict=u_domains_dict,
                        num_of_trials=num_of_trials,
                        n_list=n_list,
                        m_same_as_n=True,
                        save_data=True,
                        with_gpu=False,
                        save_directory='data/g_1/kbsa',
                        file_name=file_name,
                        verbose_inner=True,
                        verbose_outer=True,
                        verbose_inner_inner=True)

-----

In [ ]:
from numpy import arange as np_arange
from numpy import random as np_random
from numpy import array as np_array
from kbsa.hsic_utils import (get_field_file_dirs, 
                            load_mesh, 
                            load_function_space, 
                            sample_fenics_function, 
                            load_fenics_function,
                            get_gamma_matrix,
                            hsic)



/opt/miniconda3/envs/thesis-repro/lib/python3.10/site-packages/ufl/__init__.py:250: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


In [2]:
data_directory = "data/experiment_data"
data_dir_list_of_fields = get_field_file_dirs(data_directory, data_type='input_data')

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0


In [3]:
data_dir_list_of_fields[0]

'data/experiment_data/2025_11_23_17_28_38__39f9ed57ad234260839428eb77c80ecf/6617160de0e44c798503bf39547812fc/10000/input_data.npy'

In [13]:
import numpy as np
d = 3
a = np.empty((d, 5))
for i, dir in enumerate(data_dir_list_of_fields[:d]):
    a[i] = np.load(dir)
print(a)

[[6.36458662e+11 1.91411365e+03 2.01882334e+02 8.73646523e+02
  1.45966107e+00]
 [7.91105339e+11 6.34478437e+03 3.22124901e+02 9.52088227e+02
  1.01260104e+00]
 [6.01303962e+11 1.62182894e+03 2.06707361e+02 8.59206107e+02
  1.22085208e+00]]


In [4]:
valid_cdr_fields = ['fuel_field', 'oxygen_field', 'product_field', 'temp_field']
field_of_interest = valid_cdr_fields[3]

data_directory = "data/experiment_data"
data_dir_list_of_fields = get_field_file_dirs(data_directory, chosen_cdr_field=field_of_interest)

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0


In [5]:
data_dir_list_of_fields[0]

'data/experiment_data/2025_11_23_17_28_38__39f9ed57ad234260839428eb77c80ecf/6617160de0e44c798503bf39547812fc/10000/temp_field'

In [3]:
hsic(data_directory=data_directory, field_of_interest=field_of_interest, return_as_bool=True, g_constraint=700)

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0


array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.05, 0.05, 0.05],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.05, 0.05, 0.05],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.05, 0.05, 0.05],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.05, 0.05, 0.05],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.05, 0.05, 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.  , 0.05, 0.1 , 0.1 , 0.1 ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.05, 0.  , 0.05, 0.05, 0.05],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.1 , 0.05, 0.  , 0.1 , 0.1 ],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.1 , 0.05, 0.1 , 0.  , 0.1 ],
       [0.05, 0.05, 0.05, 0.05, 0.05, 0.1 , 0.05, 0.1 , 0.1 , 0.  ]])

In [3]:
from numpy import load as np_load
from pathlib import Path
from time import time_ns

In [6]:
my_mesh = load_mesh()
V = load_function_space(my_mesh)
test_domain = np_array([[0.0, 0.1], [0, 0.5]])
n = 3000
num_of_spatial_sampling_m = 100
return_as_bool = True
g_constraint = 700
my_gam_matrix = get_gamma_matrix(data_dir_list_of_fields=data_dir_list_of_fields,
                n=n,
                num_of_spatial_sampling_m=num_of_spatial_sampling_m,
                mesh=my_mesh,
                func_space_V=V,
                test_domain=test_domain,
                return_as_bool=return_as_bool,
                g_constraint=g_constraint)
my_gam_matrix.shape

(3000, 3000)

In [ ]:
import numpy as np

a = np.arange(0,10)
np.random.shuffle(a)
a 
min(a)


np.int64(0)

In [26]:
lambda_X = 1
test_domain = np_array([[0.0, 1], [0, 0.5]])
for i in range(len(test_domain)):
    lambda_curr_dom = max(test_domain[i])-min(test_domain[i])
    if lambda_curr_dom != 0:
        lambda_X *= lambda_curr_dom
print(lambda_X)

0.5


In [7]:
my_mesh = load_mesh()
V = load_function_space(my_mesh)
test_domain = np_array([[0.0, 0.1], [0, 0.5]])
num_of_spatial_sampling_M = 5
return_as_bool = True
g_constraint = 700
field_idices = np_arange(0,len(data_dir_list_of_fields))[:5]
for field_idx in field_idices:
    field_file_path = data_dir_list_of_fields[field_idx]
    sup_dir_of_file = field_file_path[:-len(Path(field_file_path).name)]
    inputs = np_load(f"{sup_dir_of_file}input_data.npy")
    print([f"{x:.2f}" for x in inputs])
    print(sample_fenics_function(field_file_path=field_file_path,
                                func_space_V=V,
                                mesh=my_mesh,
                                test_domain=test_domain,
                                num_of_spatial_sampling_M=num_of_spatial_sampling_M,
                                return_as_bool=return_as_bool,
                                g_constraint=g_constraint))
    print('\n')

    """
    inputs:
        -data_dir_list_of_fields: list of individual data point (an experiment's inputs & output-function)
        -M: number of spatial samplings from a given output-function
        -N: number of data points to use ()
    """
    

['636458662198.97', '1914.11', '201.88', '873.65', '1.46']
[0 0 0 0 1]


['791105339112.24', '6344.78', '322.12', '952.09', '1.01']
[1 1 1 1 0]


['601303961773.52', '1621.83', '206.71', '859.21', '1.22']
[1 0 0 0 0]


['1233160881181.64', '4977.73', '370.69', '884.60', '1.29']
[1 0 0 0 0]


['1266767853749.22', '4084.02', '375.66', '933.39', '1.28']
[0 0 1 1 1]




In [6]:
my_mesh = load_mesh()
V = load_function_space(my_mesh)
test_domain = np_array([[0.0, 0.1], [0.4, 0.5]])
num_of_spatial_sampling_M = 5
return_as_bool = False
g_constraint = 700
for _ in range(3):
    field_idx = np_random.randint(0, len(data_dir_list_of_fields))
    field_file_path = data_dir_list_of_fields[field_idx]
    sup_dir_of_file = field_file_path[:-len(Path(field_file_path).name)]
    inputs = np_load(f"{sup_dir_of_file}input_data.npy")
    print(inputs[3])
    print(sample_fenics_function(field_file_path=field_file_path,
                                func_space_V=V,
                                mesh=my_mesh,
                                test_domain=test_domain,
                                num_of_spatial_sampling_M=num_of_spatial_sampling_M,
                                return_as_bool=return_as_bool,
                                g_constraint=g_constraint))
    print('\n')

988.9939199539388
[0.03081803 0.46430109]
979.519567247762
[979.51956725 910.2532276  922.58323542 968.36357817 962.90566075]


993.025412044395
[0.06122626 0.41616066]
935.4076597884995
[935.40765979 912.47559025 968.80801719 982.87692437 938.14473544]


871.7764767935669
[0.05633494 0.42475314]
841.6861303912192
[841.68613039 862.9502956  832.41328671 838.88575268 854.77400164]




In [11]:
import numpy as np
from fenics import Point

In [97]:
x_vect = np.random.uniform([test_domain[0,0], test_domain[1,0]], [test_domain[0,1], test_domain[1,1]], size=(num_of_spatial_sampling_M, 2))
# x_vect

In [87]:
my_f = load_fenics_function(data_dir_list_of_fields[0])
a = 0

In [98]:
for x in x_vect:
    print(my_f(Point(x)))

865.254260744931
868.0291106760067
850.3189601987204
796.0808872457875
862.4547035286537


In [99]:
# u = np.zeros(num_of_spatial_sampling_M)
# print(u)
for myx in x_vect:
    print(my_f(myx[0], myx[1]))

865.254260744931
868.0291106760067
850.3189601987204
796.0808872457875
862.4547035286537


In [11]:
from numpy import arange as np_arange
from numpy import random as np_random
from numpy import array as np_array
from kbsa.hsic_utils import (get_K_U_sobolev_vectorized,
                            get_K_U_sobolev_looped,
                            get_data_file_dirs,
                            calculate_hsic_looped,
                            calculate_hsic_vectorized,
                            get_K_gamma)

valid_cdr_fields = ['fuel_field', 'oxygen_field', 'product_field', 'temp_field']
field_of_interest = valid_cdr_fields[3]
data_directory = "data/experiment_data"
input_data_dirs_list = get_data_file_dirs(data_directory, data_type='input_data')

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0


In [3]:
valid_cdr_fields = ['fuel_field', 'oxygen_field', 'product_field', 'temp_field']
field_of_interest = valid_cdr_fields[3]
data_directory = "data/experiment_data"
dirs = get_data_file_dirs(data_directory, data_type=field_of_interest)
print(dirs[0])
print(dirs[0].replace(field_of_interest, 'input_data.npy'))

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0
data/experiment_data/2025_11_23_17_28_38__39f9ed57ad234260839428eb77c80ecf/6617160de0e44c798503bf39547812fc/10000/temp_field
data/experiment_data/2025_11_23_17_28_38__39f9ed57ad234260839428eb77c80ecf/6617160de0e44c798503bf39547812fc/10000/input_data.npy


In [12]:
from utils.other_utils import flipStr, getIndexSuperset, directBinStrSum
def _get_u_indexSuperset_oneHot(dim_of_U, higher_order=False):
    return [flipStr(i) for i in sorted(getIndexSuperset(dim_of_U, higher_order=higher_order), key=lambda x: directBinStrSum(x))]

In [48]:
int(412341/10)

41234

In [5]:
import numpy as np

In [17]:
inputs_one_hot = _get_u_indexSuperset_oneHot(dim_of_U=5)
a = inputs_one_hot[0]
b = [key for key in inputs_one_hot[:-1] if key==a]
b

['10000']

In [16]:
n = 10
n_max = len(input_data_dirs_list)
data_dir_indices = np_arange(0, n_max)
np.random.shuffle(data_dir_indices)
if n >= n_max:
    n = n_max
input_data_dirs_list_to_use = [input_data_dirs_list[i] for i in data_dir_indices[:n]]
which_input = inputs_one_hot[0]
u_arr = np.zeros((n, 5))
for i, dir in enumerate(input_data_dirs_list_to_use):
    u_arr[i] = np.load(dir)

In [8]:
u_arr.shape

(10, 5)

In [ ]:
K_sob_vec = get_K_U_sobolev_vectorized(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr,
                                        chunk_size=2000)
K_sob_loop = get_K_U_sobolev_looped(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr)
np.allclose(K_sob_loop, K_sob_vec, rtol=1e-10, atol=1e-12)

True

In [41]:
K_sob_vec_0 = get_K_sob_matrix_vectorized(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr,
                                        chunk_size=100)

K_sob_vec_1 = get_K_sob_matrix_vectorized(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr,
                                        chunk_size=1000)

K_sob_vec_2 = get_K_sob_matrix_vectorized(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr,
                                        chunk_size=200)

K_sob_vec_3 = get_K_sob_matrix_vectorized(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr,
                                        chunk_size=int(np.ceil(n_max/2)/10))

K_sob_vec_4 = get_K_sob_matrix_vectorized(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr,
                                        chunk_size=300)

K_sob_vec_5 = get_K_sob_matrix_vectorized(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr,
                                        chunk_size=400)

K_sob_vec_6 = get_K_sob_matrix_vectorized(n=n, num_of_inputs=5, 
                                        which_input_one_hot=which_input,
                                        input_data=u_arr,
                                        chunk_size=None)
K_vec_list = [K_sob_vec_0, K_sob_vec_1, K_sob_vec_2, K_sob_vec_3, K_sob_vec_4, K_sob_vec_5, K_sob_vec_6]

for K in K_vec_list:
    print(np.allclose(K_sob_loop, K, rtol=1e-10, atol=1e-12))
    print(np.allclose(K_sob_vec_6, K, rtol=1e-10, atol=1e-12))
    print('\n')

Wall-clock time of vectorized version with chunks of 100: 0.027 (s)
Wall-clock time of vectorized version with chunks of 1000: 0.031 (s)
Wall-clock time of vectorized version with chunks of 200: 0.024 (s)
Wall-clock time of vectorized version with chunks of 282: 0.025 (s)
Wall-clock time of vectorized version with chunks of 300: 0.025 (s)
Wall-clock time of vectorized version with chunks of 400: 0.026 (s)
Wall-clock time of vectorized version with chunks of 2000: 0.031 (s)
True
True


True
True


True
True


True
True


True
True


True
True


True
True




In [1]:
from numpy import arange as np_arange
from numpy import random as np_random
from numpy import array as np_array
import numpy as np
from kbsa.hsic_utils import (get_K_U_sobolev_vectorized,
                            get_K_U_sobolev_looped,
                            get_data_file_dirs,
                            calculate_hsic_looped,
                            calculate_hsic_vectorized,
                            get_K_gamma,
                            load_mesh,
                            load_function_space)
from dolfin import Mesh, FunctionSpace, Function, XDMFFile

valid_cdr_fields = ['fuel_field', 'oxygen_field', 'product_field', 'temp_field']
field_of_interest = valid_cdr_fields[3]
data_directory = "data/experiment_data"
input_data_dirs_list = get_data_file_dirs(data_directory, data_type='input_data')

/opt/miniconda3/envs/thesis-repro/lib/python3.10/site-packages/ufl/__init__.py:250: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0


In [7]:
n = 500
n_max = len(input_data_dirs_list)
data_dir_indices = np_arange(0, n_max)
np.random.shuffle(data_dir_indices)
if n >= n_max:
    n = n_max
input_data_dirs_list_to_use = [input_data_dirs_list[i] for i in data_dir_indices[:n]]
field_data_dirs_list_to_use = [dir.replace('input_data.npy', field_of_interest) for dir in input_data_dirs_list_to_use]


which_input = '01000'
u_arr = np.zeros((n, 5))
for i, dir in enumerate(input_data_dirs_list_to_use):
    u_arr[i] = np.load(dir)

In [8]:
K_U = get_K_U_sobolev_vectorized(n=n, 
                                num_of_inputs=5, 
                                which_input_one_hot=which_input,
                                input_data=u_arr)

In [9]:
my_mesh = load_mesh()
V = load_function_space(my_mesh)
test_domain = np.array([[0.0, 0.1], [0.4, 0.5]])
num_of_spatial_sampling_M = n
return_as_bool = False
g_constraint = 700

In [10]:
K_gamma = get_K_gamma(field_data_dirs_list=field_data_dirs_list_to_use,
                        n=n,
                        num_of_spatial_sampling_m=n,
                        mesh=my_mesh,
                        func_space_V=V,
                        test_domain=test_domain,
                        return_as_bool=return_as_bool,
                        g_constraint=g_constraint)

Wall-clock time of spatial_sampling: 14.451 (s)
Wall-clock time of approximate_set_lebesgue: 0.043 (s)
Wall-clock time of sigma_squared: 0.000 (s)
Wall-clock time of exponentiate_K_gamma: 0.001 (s)
Wall-clock time of fill_diag_of_K_gamma: 0.000 (s)


In [6]:
hsic_looped = calculate_hsic_looped(K_U=K_U, K_gamma=K_gamma, verbose=True)
hsic_vec = calculate_hsic_vectorized(K_U=K_U, K_gamma=K_gamma, verbose=True)

Wall-clock time of calculate_hsic_looped: 0.002 (s)
Wall-clock time of calculate_hsic_vectorized: 0.001 (s)


In [12]:
print(hsic_looped)
print(hsic_vec)

14985125.076224094
14985125.07622392


----

In [1]:
from kbsa.hsic import hsic

/opt/miniconda3/envs/thesis-repro/lib/python3.10/site-packages/ufl/__init__.py:250: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


In [2]:
# np_arr([u_A, u_E, u_T_i, u_T_o, u_phi])

In [2]:
a, b = [32.3, 11.1]
print(a,b)

32.3 11.1


In [3]:
from numpy import array as np_array
valid_cdr_fields = ['fuel_field', 'oxygen_field', 'product_field', 'temp_field']
field_of_interest = valid_cdr_fields[3]
data_directory = "data/experiment_data"
test_domain = np_array([[0,1],[0,0.5]])
u_domain_specs = [{'distribution_type': 'log_uniform', 'min': 5.5e11, 'max': 1.5e12},
                {'distribution_type': 'log_uniform', 'min': 1.5e3, 'max': 9.5e3},
                {'distribution_type': 'uniform', 'min': 200, 'max': 400},
                {'distribution_type': 'uniform', 'min': 850, 'max': 1000},
                {'distribution_type': 'uniform', 'min': 0.5, 'max': 1.5}]
key_map_2d_cdr = {'10000': 'A', 
                '01000': 'E',
                '00100': 'T_i',
                '00010': 'T_o',
                '00001': 'phi'}
n = 100
m = n
hsic(data_directory=data_directory,
    field_of_interest=field_of_interest,
    n=n,
    num_of_spatial_sampling_m=m,
    test_domain=test_domain,
    u_domain_specs=u_domain_specs,
    g_constraint=650,
    shuffle_inputs=True,
    u_one_hot_key_map=key_map_2d_cdr)


Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0
Using 100 data points.


{'A': np.float64(0.5674343924376511),
 'E': np.float64(-0.7527094805599106),
 'T_i': np.float64(0.22831384251032194),
 'T_o': np.float64(0.7067186726051509),
 'phi': np.float64(0.39366264607952256)}

In [3]:
from kbsa.hsic_utils import get_u_index_superset_one_hot_binstrs
get_u_index_superset_one_hot_binstrs(5)

['10000', '01000', '00100', '00010', '00001', '11111']

In [ ]:
n = 2999
size = 14
n_padded_up = n + (size-n%size)
n_padded_down = n - (n%size)

n_max = 3010
if n_padded_up > n_max:
    print(f'Using {n-n_padded_down} less data points to ensure MPI parallelization. Need {n_padded_up} data points at the next parallelization increment using {size} MPI tasks/core.')
    n = n_padded_down
else:
    print(f'Using {n_padded_up-n} extra data points to ensure MPI parallelization.')
    n = n_padded_up
print(n)
max_jobs = (n + size - 1) // size 
total_num_of_pad = 0
for rank in range(size):
    indices = range(rank, n, size)
    padded_indices = [i for i in indices]
    num_of_padded_runs_in_curr_rank = 0
    while len(padded_indices) < max_jobs:
        padded_indices.append(None)
        num_of_padded_runs_in_curr_rank += 1
    total_num_of_pad += num_of_padded_runs_in_curr_rank
total_num_of_pad

Using 11 extra data points to ensure MPI parallelization.
3010


0