In [2]:
from kbsa.kbsa_main import run_kbsa, get_kbsa_datafile_name
import numpy as np
from utils import numeric_models as nm
from utils import plotter
from dolfin import Point
from kbsa.model_generators import get_CDR

/opt/miniconda3/envs/thesis-repro/lib/python3.10/site-packages/ufl/__init__.py:250: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


In [ ]:
def gen_log_uniform(a, b, size=None):
    u = np.random.uniform(np.log(a), np.log(b), size=size)
    return np.exp(u)

def gen_uniform(a, b, size=None):
    return np.random.uniform(a, b, size=size)

def transform_logUnif_to_unitUnif(a, b, log_unif_samples):
    transformed_samples = (np.log(log_unif_samples) - np.log(a))/(np.log(b)-np.log(a))
    assert np.sum((transformed_samples>1)) + np.sum((transformed_samples<0))==0
    return transformed_samples

def transform_unif_to_unifUnif(a, b, unif_samples):
    transformed_samples = (unif_samples-a)/(b-a)
    assert np.sum((transformed_samples>1)) + np.sum((transformed_samples<0))==0
    return transformed_samples
# NOTE: NEED TO SAVE THESE GENERATED SAMPLES TO A FILE.
N = 1
A = gen_log_uniform(a=5.5e11, b=1.5e12, size=(6, N))
E = gen_log_uniform(a=1.5e3, b=9.5e3, size=(6, N))
T_i = gen_uniform(a=200, b=400,size=(6, N))
T_o = gen_uniform(a=850, b=1000,size=(6, N))
phi = gen_uniform(a=0.5, b=1.5,size=(6, N))
print(A)
print(E)
print(T_i)
print(T_o)
print(phi)
u_input = np.array([A, E, T_i, T_o, phi])
u_input.shape
# a = np.random.uniform(0.0001,10)
# b = np.random.uniform(10,10000)

# log_unif_samples = gen_log_uniform(a=a, b=b, size=1000)
# transform_logUnif_to_unitUnif(a=a,b=b,log_unif_samples=log_unif_samples)

# unif_samples = gen_uniform(a=a,b=b,size=10000)
# transform_unif_to_unifUnif(a=a,b=b,unif_samples=unif_samples)

# from scipy import stats
# logUnifs = stats.loguniform.rvs(a,b, size=100000)

[[1.00722635e+12]
 [1.12835799e+12]
 [8.39612801e+11]
 [6.79660645e+11]
 [6.50614404e+11]
 [7.13614533e+11]]
[[7105.37021692]
 [1793.15797711]
 [2187.09169571]
 [1545.91187656]
 [1656.26412328]
 [4186.13056899]]
[[222.51348591]
 [347.22879053]
 [245.20513262]
 [356.89715207]
 [335.70606736]
 [221.66391753]]
[[893.77104903]
 [958.29211419]
 [989.64296937]
 [898.30924557]
 [886.29545202]
 [938.89936095]]
[[1.22925448]
 [0.82485052]
 [1.30702912]
 [0.57393935]
 [1.03666073]
 [1.36010686]]


(5, 6, 1)

In [ ]:

def unit_uniform_rng(size, type):
    if type == 'A':
        np
        return np.random.uniform(5.5e11, 1.5e12, size=size)
    return 


def generate_cdr_sample():
    fuel_rng = 
    model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.1, 
                            'num_steps':10, 
                            'return_bool': False,
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}

SyntaxError: incomplete input (119094012.py, line 1)

0.08

In [30]:
models_list = ['cdr']
kernel_types_list = ['sobolev']
model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.05, 
                            'num_steps': 100, 
                            'return_bool': False,
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}
x_domains_dict = {'cdr': np.array([[0.2,0.3],[0.01,0.2]])}
u_domains_dict = {'cdr': np.array([[5e11,1.5e12],[1.5e3,9.5e3],[850,1000],[200,400],[0.5,1.5]])}

In [ ]:
# from kbsa.utils_kbsa import _get_u_samples_arr_to_kernel, _get_u_samples_arr, _get_u_indexSuperset_oneHot
# u_domain = u_domains_dict['cdr']
# # dim_of_U = len(u_domain)
# dim_of_U=5
# u_indexSuperset_oneHot = _get_u_indexSuperset_oneHot(dim_of_U=dim_of_U, higher_order=False)
# dim_of_u_superset = len(u_indexSuperset_oneHot)
# # f"{u_indexSuperset_oneHot}".replace('[','').replace(']','').replace('\'','').replace('\'','')

In [221]:
n = 1
u_samples_arr_to_kernel = _get_u_samples_arr_to_kernel(dim_of_u_superset=dim_of_u_superset, dim_of_U=dim_of_U, n=n)
u_samples_arr = _get_u_samples_arr(u_samples_arr_to_kernel=u_samples_arr_to_kernel, u_domain=u_domain, dim_of_U=dim_of_U,dim_of_u_superset=dim_of_u_superset, gamma_type='cdr')

In [222]:
u_test = u_samples_arr[0][0]
u_test

array([1.30010284e+12, 4.92816461e+03, 9.91053830e+02, 3.41828170e+02,
       1.11131353e+00])

In [29]:
0.05 / 100

0.0005

In [31]:
my_fen = get_CDR(params=model_params_dict['cdr'])

In [32]:
result_fens = my_fen(u=u_input[:,0,0])

Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.


In [7]:
x_0 = np.random.uniform(0,1)
x_1 = np.random.uniform(0,0.5)
print(f"{x_0}, {x_1}")

0.37559745729403393, 0.24167799822509378


In [227]:
type(result_fens)

list

In [11]:
from dolfin import File, XDMFFile, Constant, conditional, le, project
from dolfin import Mesh,FunctionSpace,Function

In [12]:
mesh = Mesh()
with XDMFFile("data/CDR/mesh_save_dir/rectangle.xdmf") as xdmf:
    xdmf.read(mesh)

In [13]:
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/fuel_field') as xdmf_1:
    xdmf_1.write_checkpoint(result_fens[0], 'fuel_field', 0, XDMFFile.Encoding.HDF5, append=False)
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/oxygen_field') as xdmf_2:
    xdmf_2.write_checkpoint(result_fens[1], 'oxygen_field', 0, XDMFFile.Encoding.HDF5, append=False)
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/product_field') as xdmf_3:
    xdmf_3.write_checkpoint(result_fens[2], 'product_field', 0, XDMFFile.Encoding.HDF5, append=False)   
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/temp_field') as xdmf_4:
    xdmf_4.write_checkpoint(result_fens[3], 'temp_field', 0, XDMFFile.Encoding.HDF5, append=False)

In [44]:
from datetime import datetime
import time 
print(time.time_ns())
datetime.now().strftime("%Y_%m_%d")

1763319986155429000


'2025_11_16'

In [213]:
for j in range(4):
    print([i for i in range(j, 6, 4)])

[0, 4]
[1, 5]
[2]
[3]


In [163]:
from datetime import datetime
import time, uuid
from os import path, makedirs

save_dir = "data/CDR/experimental_data"

N = 2
parent_uid = str(uuid.uuid4().hex)
folder_name_exprim_parent = "exprim_start_" + datetime.now().strftime("%Y_%m_%d_%H_%M_%S__uid_") + parent_uid
for i in range(N):
    curr_date = datetime.now().strftime("%Y_%m_%d")  
    curr_itr_file_uid = f"{time.time_ns()}_{str(uuid.uuid4().hex)}"
    folder_full_path = f"{save_dir}/{folder_name_exprim_parent}/uid_{curr_itr_file_uid}"
    makedirs(folder_full_path, exist_ok=True)
    with open(f"{folder_full_path}/metadata_uid_{curr_itr_file_uid}.txt", "w") as f:
        f.write(f"parent_uid_{parent_uid};\ncurr_itr_uid_{curr_itr_file_uid};")

    # print(folder_full_path)

# formatted = datetime.now().isoformat(timespec='nanoseconds')
# print(formatted)
# print(uuid)
# 
# folder_name_exprim_parent = "exprim_start" + datetime.now().strftime("%Y_%m_%d__%H_%M_%S")
# curr_itr = 1
# curr_itr_datetime = datetime.now().strftime("%Y_%m_%d__%H_%M_%S")
#  = path.join(dir_to_save, folder_name)
# 
# makedirs(curr_output_dir, exist_ok=True)

In [8]:
from dolfin import Mesh, FunctionSpace, Function, XDMFFile
mesh = Mesh()
with XDMFFile("data/CDR/mesh_save_dir/rectangle.xdmf") as xdmf:
    xdmf.read(mesh)
    
V_1 = FunctionSpace(mesh, 'CG', 1) 
V_2 = FunctionSpace(mesh, 'CG', 1)
V_3 = FunctionSpace(mesh, 'CG', 1)
V_4 = FunctionSpace(mesh, 'CG', 1)
fuel_field_t_now = Function(V_1)
oxyxen_field_t_now = Function(V_2)
product_field_t_now = Function(V_3)
temp_field_t_now = Function(V_4)

with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/fuel_field') as xdmf_1:
    xdmf_1.read_checkpoint(fuel_field_t_now, 'fuel_field', 0)
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/oxygen_field') as xdmf_2:
    xdmf_2.read_checkpoint(oxyxen_field_t_now, 'oxygen_field', 0)
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/product_field') as xdmf_3:
    xdmf_3.read_checkpoint(product_field_t_now, 'product_field', 0) 
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/temp_field') as xdmf_4:
    xdmf_4.read_checkpoint(temp_field_t_now, 'temp_field', 0)

In [26]:
from dolfin import Point
# x_0 = np.random.uniform(0,1)
# x_1 = np.random.uniform(0,0.5)
x_0 = 0
x_1 = 0
print(fuel_field_t_now(Point([x_0, x_1])))
print(oxyxen_field_t_now(Point([x_0, x_1])))
print(product_field_t_now(Point([x_0, x_1])))
print(temp_field_t_now(Point([x_0, x_1])))

1.363942777658423e-20
1.0944249429186036e-19
1.642288553472851e-20
222.42672798573562


In [164]:
from scipy import stats
a = np.random.uniform(0.0001,10)
b = np.random.uniform(10,10000)
logUnifs = stats.loguniform.rvs(a,b, size=100000)
np.sum(((np.log(logUnifs) - np.log(a))/(np.log(b)-np.log(a))>1)) + np.sum(((np.log(logUnifs) - np.log(a))/(np.log(b)-np.log(a))<0))

np.int64(0)

In [ ]:
x_0 = np.random.uniform(0,1)
x_1 = np.random.uniform(0,0.5)
[f(Point([x_0, x_1])) for f in result_fens]

In [ ]:
cdr_model = nm.model(model_type='cdr', 
                    t_end_cdr=0.5, 
                    num_steps_cdr=100, 
                    output_paraview=False, 
                    mesh_2D_dir='data/CDR/mesh_save_dir/rectangle.xdmf', 
                    mesh_steps=0.025)

In [ ]:
cdr_model.output_paraview = True
cdr_model.get_cdr(reset=True, t_end=0.5, num_steps=100)
cdr_model.save_curr_cdr_output_to_file()
plotter.plot(model=cdr_model, plot_type='2D_mesh')

In [ ]:
models_list = ['cdr']
kernel_types_list = ['sobolev']
model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.1, 
                            'num_steps':10, 
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}
x_domains_dict = {'cdr': np.array([[0.2,0.3],[0.01,0.2]])}
u_domains_dict = {'cdr': np.array([[5e11,1.5e12],[1.5e3,9.5e3],[850,1000],[200,400],[0.5,1.5]])}
num_of_trials = 20
# num_of_trials = 5
n_list = [500]
# n_list = [50]
hsic_types_dict = {'unbiased': False, 'biased': False, 'R2': False, 'fellman': True}


In [ ]:
for n_list in N_list_list:
        file_name = get_kbsa_datafile_name(models_list=models_list, 
                                x_domains_dict=x_domains_dict, 
                                kernel_types_list=kernel_types_list, 
                                hsic_types_dict=hsic_types_dict, 
                                n_list=n_list, 
                                num_of_trials=num_of_trials,
                                model_params_dict=model_params_dict)

        data = run_kbsa(hsic_types_dict=hsic_types_dict,
                        kernel_types_list=kernel_types_list,
                        models_list=models_list,
                        model_params_dict=model_params_dict,
                        x_domains_dict=x_domains_dict,
                        sample_x_from_mesh=True,
                        u_domains_dict=u_domains_dict,
                        num_of_trials=num_of_trials,
                        n_list=n_list,
                        m_same_as_n=True,
                        save_data=True,
                        with_gpu=False,
                        save_directory='data/g_1/kbsa',
                        file_name=file_name,
                        verbose_inner=True,
                        verbose_outer=True,
                        verbose_inner_inner=True)