-----

##### Simulation time estimation

In [1]:
t_per_itr = 46.215293/1000
print(f"time per iter: {t_per_itr:0.3} s")
N = 1000
total_time_steps = 500
total_simulation_time = N * total_time_steps * t_per_itr
print(f"Total simulation time per node: {total_simulation_time/3600:0.4} hours")
num_of_nodes = 12
print(f"Total simulation time on {num_of_nodes} nodes: {total_simulation_time/(3600*num_of_nodes):0.4} hours")

time per iter: 0.0462 s
Total simulation time per node: 6.419 hours
Total simulation time on 12 nodes: 0.5349 hours


Simulation data storage requirement estimation

In [ ]:
data_req_per_sampling_est_bytes = 1706345  #bytes
#1 GiB = 1024**3 B
data_req_per_sampling_est_GiB = 0.0015891576185822 #GiB
total_data_storage_req_est = 6*N*data_req_per_sampling_est_GiB
print(f"Total data storage requirement: {total_data_storage_req_est:0.4} GB")

Total data storage requirement: 47.67 GB


-----

In [ ]:
u_A = gen_log_uniform(a=5.5e11, b=1.5e12, size=6)
u_E = gen_log_uniform(a=1.5e3, b=9.5e3, size=6)
u_T_i = gen_uniform(a=200, b=400,size=6)
u_T_o = gen_uniform(a=850, b=1000,size=6)
u_phi = gen_uniform(a=0.5, b=1.5,size=6)
u_input = np_arr([u_A, u_E, u_T_i, u_T_o, u_phi])
print(u_input[:,0])
np_save(file="to_save.npy", arr=u_input[:,0])

[8.14550529e+11 2.48418238e+03 3.49455307e+02 9.75168659e+02
 7.18757882e-01]


In [2]:
from kbsa.kbsa_main import run_kbsa, get_kbsa_datafile_name
import numpy as np
from utils import numeric_models as nm
from utils import plotter
from dolfin import Point
from kbsa.model_generators import get_CDR

/opt/miniconda3/envs/thesis-repro/lib/python3.10/site-packages/ufl/__init__.py:250: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


In [96]:
import time
time.time()

1763486338.170223

In [2]:
def gen_log_uniform(a, b, size=None):
    u = np.random.uniform(np.log(a), np.log(b), size=size)
    return np.exp(u)

def gen_uniform(a, b, size=None):
    return np.random.uniform(a, b, size=size)

def transform_logUnif_to_unitUnif(a, b, log_unif_samples):
    transformed_samples = (np.log(log_unif_samples) - np.log(a))/(np.log(b)-np.log(a))
    assert np.sum((transformed_samples>1)) + np.sum((transformed_samples<0))==0
    return transformed_samples

def transform_unif_to_unifUnif(a, b, unif_samples):
    transformed_samples = (unif_samples-a)/(b-a)
    assert np.sum((transformed_samples>1)) + np.sum((transformed_samples<0))==0
    return transformed_samples
# NOTE: NEED TO SAVE THESE GENERATED SAMPLES TO A FILE.
N = 1
A = gen_log_uniform(a=5.5e11, b=1.5e12, size=(6, N))
E = gen_log_uniform(a=1.5e3, b=9.5e3, size=(6, N))
T_i = gen_uniform(a=200, b=400,size=(6, N))
T_o = gen_uniform(a=850, b=1000,size=(6, N))
phi = gen_uniform(a=0.5, b=1.5,size=(6, N))
print(A)
print(E)
print(T_i)
print(T_o)
print(phi)
u_input = np.array([A, E, T_i, T_o, phi])
u_input.shape
# a = np.random.uniform(0.0001,10)
# b = np.random.uniform(10,10000)

# log_unif_samples = gen_log_uniform(a=a, b=b, size=1000)
# transform_logUnif_to_unitUnif(a=a,b=b,log_unif_samples=log_unif_samples)

# unif_samples = gen_uniform(a=a,b=b,size=10000)
# transform_unif_to_unifUnif(a=a,b=b,unif_samples=unif_samples)

# from scipy import stats
# logUnifs = stats.loguniform.rvs(a,b, size=100000)

[[6.61623447e+11]
 [9.91983969e+11]
 [5.66294666e+11]
 [9.47384795e+11]
 [5.57158738e+11]
 [7.64591287e+11]]
[[2081.28436244]
 [1903.37260827]
 [7193.58349055]
 [1616.05064585]
 [1833.84470542]
 [2839.98347418]]
[[229.17629916]
 [328.50187739]
 [265.32090157]
 [236.94244193]
 [230.2279453 ]
 [202.33000878]]
[[940.22099124]
 [893.93414623]
 [874.01820557]
 [992.53286097]
 [942.95634124]
 [899.19643981]]
[[1.46052207]
 [1.31020706]
 [0.71753703]
 [1.06674247]
 [0.79456171]
 [1.47144419]]


(5, 6, 1)

In [100]:
for i, s in enumerate(['a', 'b']):
    print(s, i)

a 0
b 1


In [ ]:

def unit_uniform_rng(size, type):
    if type == 'A':
        np
        return np.random.uniform(5.5e11, 1.5e12, size=size)
    return 


def generate_cdr_sample():
    fuel_rng = 
    model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.1, 
                            'num_steps':5, 
                            'return_bool': False,
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}

SyntaxError: incomplete input (119094012.py, line 1)

In [52]:
0.05/100

0.0001*300
0.05/0.0001

500.0

In [4]:
models_list = ['cdr']
kernel_types_list = ['sobolev']
model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.05, 
                            'num_steps': 5, 
                            'return_bool': False,
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}
x_domains_dict = {'cdr': np.array([[0.2,0.3],[0.01,0.2]])}
u_domains_dict = {'cdr': np.array([[5e11,1.5e12],[1.5e3,9.5e3],[850,1000],[200,400],[0.5,1.5]])}

In [ ]:
# from kbsa.utils_kbsa import _get_u_samples_arr_to_kernel, _get_u_samples_arr, _get_u_indexSuperset_oneHot
# u_domain = u_domains_dict['cdr']
# # dim_of_U = len(u_domain)
# dim_of_U=5
# u_indexSuperset_oneHot = _get_u_indexSuperset_oneHot(dim_of_U=dim_of_U, higher_order=False)
# dim_of_u_superset = len(u_indexSuperset_oneHot)
# # f"{u_indexSuperset_oneHot}".replace('[','').replace(']','').replace('\'','').replace('\'','')

In [3]:
n = 1
u_samples_arr_to_kernel = _get_u_samples_arr_to_kernel(dim_of_u_superset=dim_of_u_superset, dim_of_U=dim_of_U, n=n)
u_samples_arr = _get_u_samples_arr(u_samples_arr_to_kernel=u_samples_arr_to_kernel, u_domain=u_domain, dim_of_U=dim_of_U,dim_of_u_superset=dim_of_u_superset, gamma_type='cdr')

NameError: name '_get_u_samples_arr_to_kernel' is not defined

In [3]:
u_test = u_samples_arr[0][0]
u_test

NameError: name 'u_samples_arr' is not defined

In [29]:
0.05 / 100

0.0005

In [4]:
my_fen = get_CDR(params=model_params_dict['cdr'])

In [5]:
result_fens = my_fen(u=u_input[:,0,0])

Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.


In [10]:
x_0 = np.random.uniform(0,1)
x_1 = np.random.uniform(0,0.5)
print(f"{x_0}, {x_1}")

0.019651405462366434, 0.3450282292399109


In [227]:
type(result_fens)

list

In [6]:
from dolfin import File, XDMFFile, Constant, conditional, le, project
from dolfin import Mesh,FunctionSpace,Function

In [7]:
mesh = Mesh()
with XDMFFile("data/CDR/mesh_save_dir/rectangle.xdmf") as xdmf:
    xdmf.read(mesh)

In [8]:
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/fuel_field') as xdmf_1:
    xdmf_1.write_checkpoint(result_fens[0], 'fuel_field', 0, XDMFFile.Encoding.HDF5, append=False)
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/oxygen_field') as xdmf_2:
    xdmf_2.write_checkpoint(result_fens[1], 'oxygen_field', 0, XDMFFile.Encoding.HDF5, append=False)
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/product_field') as xdmf_3:
    xdmf_3.write_checkpoint(result_fens[2], 'product_field', 0, XDMFFile.Encoding.HDF5, append=False)   
with XDMFFile(mesh.mpi_comm(), 'data/CDR/state_saves/temp_field') as xdmf_4:
    xdmf_4.write_checkpoint(result_fens[3], 'temp_field', 0, XDMFFile.Encoding.HDF5, append=False)

In [44]:
from datetime import datetime
import time 
print(time.time_ns())
datetime.now().strftime("%Y_%m_%d")

1763319986155429000


'2025_11_16'

In [213]:
for j in range(4):
    print([i for i in range(j, 6, 4)])

[0, 4]
[1, 5]
[2]
[3]


In [163]:
from datetime import datetime
import time, uuid
from os import path, makedirs

save_dir = "data/CDR/experimental_data"

N = 2
parent_uid = str(uuid.uuid4().hex)
folder_name_exprim_parent = "exprim_start_" + datetime.now().strftime("%Y_%m_%d_%H_%M_%S__uid_") + parent_uid
for i in range(N):
    curr_date = datetime.now().strftime("%Y_%m_%d")  
    curr_itr_file_uid = f"{time.time_ns()}_{str(uuid.uuid4().hex)}"
    folder_full_path = f"{save_dir}/{folder_name_exprim_parent}/uid_{curr_itr_file_uid}"
    makedirs(folder_full_path, exist_ok=True)
    with open(f"{folder_full_path}/metadata_uid_{curr_itr_file_uid}.txt", "w") as f:
        f.write(f"parent_uid_{parent_uid};\ncurr_itr_uid_{curr_itr_file_uid};")

    # print(folder_full_path)

# formatted = datetime.now().isoformat(timespec='nanoseconds')
# print(formatted)
# print(uuid)
# 
# folder_name_exprim_parent = "exprim_start" + datetime.now().strftime("%Y_%m_%d__%H_%M_%S")
# curr_itr = 1
# curr_itr_datetime = datetime.now().strftime("%Y_%m_%d__%H_%M_%S")
#  = path.join(dir_to_save, folder_name)
# 
# makedirs(curr_output_dir, exist_ok=True)

In [ ]:
from dolfin import Mesh, FunctionSpace, Function, XDMFFile

mesh = Mesh()
with XDMFFile("data/CDR/mesh_save_dir/rectangle.xdmf") as xdmf:
    xdmf.read(mesh)
    
V_1 = FunctionSpace(mesh, 'CG', 1) 
V_2 = FunctionSpace(mesh, 'CG', 1)
V_3 = FunctionSpace(mesh, 'CG', 1)
V_4 = FunctionSpace(mesh, 'CG', 1)
fuel_field_t_now = Function(V_1)
oxyxen_field_t_now = Function(V_2)
product_field_t_now = Function(V_3)
temp_field_t_now = Function(V_4)

a_load_path = 'data/CDR/state_saves'
sample_load_path = 'data/experiment_data/2025_11_21_16_49_53__f9d9617b0d0d44cdaa5fd061a1734cad/94137314f05046f0a4bdac50a5d03bef/00001'

with XDMFFile(mesh.mpi_comm(), f'{sample_load_path}/fuel_field') as xdmf_1:
    xdmf_1.read_checkpoint(fuel_field_t_now, 'fuel_field', 0)
with XDMFFile(mesh.mpi_comm(), f'{sample_load_path}/oxygen_field') as xdmf_2:
    xdmf_2.read_checkpoint(oxyxen_field_t_now, 'oxygen_field', 0)
with XDMFFile(mesh.mpi_comm(), f'{sample_load_path}/product_field') as xdmf_3:
    xdmf_3.read_checkpoint(product_field_t_now, 'product_field', 0) 
with XDMFFile(mesh.mpi_comm(), f'{sample_load_path}/temp_field') as xdmf_4:
    xdmf_4.read_checkpoint(temp_field_t_now, 'temp_field', 0)

In [44]:
from dolfin import Point
from numpy import random as np_random
x_0 = np_random.uniform(0,1)
x_1 = np_random.uniform(0,0.5)
# x_0 = 0.25
# x_1 = 0.1
print(fuel_field_t_now(Point([x_0, x_1])))
print(oxyxen_field_t_now(Point([x_0, x_1])))
print(product_field_t_now(Point([x_0, x_1])))
print(temp_field_t_now(Point([x_0, x_1])))

0.007937835148330914
0.06364653345486973
0.005361466784768133
789.9353790969775


In [45]:
from numpy import load as np_load
inputs_u = np_load(f"{sample_load_path}/input_data.npy")
inputs_u

array([5.84078611e+11, 6.24035019e+03, 3.85954369e+02, 8.62347811e+02,
       9.79661178e-01])

In [2]:
size = 12
N = 1000
max_jobs = (N + size - 1) // size
print(max_jobs)
num_extra_runs = 0
for rank in range(size):
    adj_print = False
    A = range(rank, N, size)
    job_indices = [i for i in A]
    if len(A) < max_jobs:
        job_indices.append(None)
        adj_print = True
        num_extra_runs += 1
    print('Final job_indices:',job_indices)
print(num_extra_runs)

84
Final job_indices: [0, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120, 132, 144, 156, 168, 180, 192, 204, 216, 228, 240, 252, 264, 276, 288, 300, 312, 324, 336, 348, 360, 372, 384, 396, 408, 420, 432, 444, 456, 468, 480, 492, 504, 516, 528, 540, 552, 564, 576, 588, 600, 612, 624, 636, 648, 660, 672, 684, 696, 708, 720, 732, 744, 756, 768, 780, 792, 804, 816, 828, 840, 852, 864, 876, 888, 900, 912, 924, 936, 948, 960, 972, 984, 996]
Final job_indices: [1, 13, 25, 37, 49, 61, 73, 85, 97, 109, 121, 133, 145, 157, 169, 181, 193, 205, 217, 229, 241, 253, 265, 277, 289, 301, 313, 325, 337, 349, 361, 373, 385, 397, 409, 421, 433, 445, 457, 469, 481, 493, 505, 517, 529, 541, 553, 565, 577, 589, 601, 613, 625, 637, 649, 661, 673, 685, 697, 709, 721, 733, 745, 757, 769, 781, 793, 805, 817, 829, 841, 853, 865, 877, 889, 901, 913, 925, 937, 949, 961, 973, 985, 997]
Final job_indices: [2, 14, 26, 38, 50, 62, 74, 86, 98, 110, 122, 134, 146, 158, 170, 182, 194, 206, 218, 230, 242, 254, 266, 278, 290, 30

In [164]:
from scipy import stats
a = np.random.uniform(0.0001,10)
b = np.random.uniform(10,10000)
logUnifs = stats.loguniform.rvs(a,b, size=100000)
np.sum(((np.log(logUnifs) - np.log(a))/(np.log(b)-np.log(a))>1)) + np.sum(((np.log(logUnifs) - np.log(a))/(np.log(b)-np.log(a))<0))

np.int64(0)

In [ ]:
x_0 = np.random.uniform(0,1)
x_1 = np.random.uniform(0,0.5)
[f(Point([x_0, x_1])) for f in result_fens]

In [ ]:
import numpy as np
from utils import numeric_models as nm

In [3]:
cdr_model = nm.model(model_type='cdr', 
                    t_end_cdr=0.05, 
                    num_steps_cdr=50, 
                    output_paraview=False, 
                    mesh_2D_dir='data/CDR/mesh_save_dir/rectangle.xdmf', 
                    mesh_steps=0.025)

In [4]:
cdr_model.output_paraview = True
cdr_model.get_cdr()
# cdr_model.save_curr_cdr_output_to_file()
# plotter.plot(model=cdr_model, plot_type='2D_mesh')

Calling FFC just-in-time (JIT) compiler, this may take some time.
Calling FFC just-in-time (JIT) compiler, this may take some time.


In [ ]:
models_list = ['cdr']
kernel_types_list = ['sobolev']
model_params_dict = {'cdr': {'mesh_2D_dir': 'data/CDR/mesh_save_dir/rectangle.xdmf', 
                            'mesh_steps': 0.025, 
                            't_end': 0.1, 
                            'num_steps':10, 
                            'g_ineq_c': {'fuel': 0.02, 'oxygen': 0.14, 'product': 0.014, 'temp': 900}}}
x_domains_dict = {'cdr': np.array([[0.2,0.3],[0.01,0.2]])}
u_domains_dict = {'cdr': np.array([[5e11,1.5e12],[1.5e3,9.5e3],[850,1000],[200,400],[0.5,1.5]])}
num_of_trials = 20
# num_of_trials = 5
n_list = [500]
# n_list = [50]
hsic_types_dict = {'unbiased': False, 'biased': False, 'R2': False, 'fellman': True}


In [ ]:
for n_list in N_list_list:
        file_name = get_kbsa_datafile_name(models_list=models_list, 
                                x_domains_dict=x_domains_dict, 
                                kernel_types_list=kernel_types_list, 
                                hsic_types_dict=hsic_types_dict, 
                                n_list=n_list, 
                                num_of_trials=num_of_trials,
                                model_params_dict=model_params_dict)

        data = run_kbsa(hsic_types_dict=hsic_types_dict,
                        kernel_types_list=kernel_types_list,
                        models_list=models_list,
                        model_params_dict=model_params_dict,
                        x_domains_dict=x_domains_dict,
                        sample_x_from_mesh=True,
                        u_domains_dict=u_domains_dict,
                        num_of_trials=num_of_trials,
                        n_list=n_list,
                        m_same_as_n=True,
                        save_data=True,
                        with_gpu=False,
                        save_directory='data/g_1/kbsa',
                        file_name=file_name,
                        verbose_inner=True,
                        verbose_outer=True,
                        verbose_inner_inner=True)

-----

In [1]:
from numpy import arange as np_arange
from numpy import random as np_random
from numpy import array as np_array
from kbsa.hsic_utils import (get_field_file_dirs, 
                            load_mesh, 
                            load_function_space, 
                            sample_fenics_function, 
                            load_fenics_function, 
                            approximate_k_set,
                            get_gamma_matrix)

/opt/miniconda3/envs/thesis-repro/lib/python3.10/site-packages/ufl/__init__.py:250: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources


In [2]:
valid_cdr_fields = ['fuel_field', 'oxygen_field', 'product_field', 'temp_field']
field_of_interest = valid_cdr_fields[3]

data_directory = "data/experiment_data"
data_dir_list_of_fields = get_field_file_dirs(data_directory, chosen_cdr_field=field_of_interest)

Num_of_parent_skips: 1
num_of_sub_folder_skips: 0
num_of_sub_sub_folder_skips: 0


In [3]:
from numpy import load as np_load
from pathlib import Path
from time import time_ns

In [5]:
my_mesh = load_mesh()
V = load_function_space(my_mesh)
test_domain = np_array([[0.0, 0.1], [0, 0.5]])
n = 3
num_of_spatial_sampling_m = 10000
return_as_bool = True
g_constraint = 700
# t0 = time_ns()
my_gam_matrix = get_gamma_matrix(data_dir_list_of_fields=data_dir_list_of_fields,
                n=n,
                num_of_spatial_sampling_m=num_of_spatial_sampling_m,
                mesh=my_mesh,
                func_space_V=V,
                test_domain=test_domain,
                return_as_bool=return_as_bool,
                g_constraint=g_constraint)
# t1 = time_ns()
# print(f'{(t1-t0)*10**-9:0.3f} s')
my_gam_matrix

array([[0.      , 0.028945, 0.02933 ],
       [0.028945, 0.      , 0.036145],
       [0.02933 , 0.036145, 0.      ]])

In [ ]:
import numpy as np

a = np.arange(0,10)
np.random.shuffle(a)
a 
min(a)


np.int64(0)

In [26]:
lambda_X = 1
test_domain = np_array([[0.0, 1], [0, 0.5]])
for i in range(len(test_domain)):
    lambda_curr_dom = max(test_domain[i])-min(test_domain[i])
    if lambda_curr_dom != 0:
        lambda_X *= lambda_curr_dom
print(lambda_X)

0.5


In [7]:
my_mesh = load_mesh()
V = load_function_space(my_mesh)
test_domain = np_array([[0.0, 0.1], [0, 0.5]])
num_of_spatial_sampling_M = 5
return_as_bool = True
g_constraint = 700
field_idices = np_arange(0,len(data_dir_list_of_fields))[:5]
for field_idx in field_idices:
    field_file_path = data_dir_list_of_fields[field_idx]
    sup_dir_of_file = field_file_path[:-len(Path(field_file_path).name)]
    inputs = np_load(f"{sup_dir_of_file}input_data.npy")
    print([f"{x:.2f}" for x in inputs])
    print(sample_fenics_function(field_file_path=field_file_path,
                                func_space_V=V,
                                mesh=my_mesh,
                                test_domain=test_domain,
                                num_of_spatial_sampling_M=num_of_spatial_sampling_M,
                                return_as_bool=return_as_bool,
                                g_constraint=g_constraint))
    print('\n')

    """
    inputs:
        -data_dir_list_of_fields: list of individual data point (an experiment's inputs & output-function)
        -M: number of spatial samplings from a given output-function
        -N: number of data points to use ()
    """
    

['636458662198.97', '1914.11', '201.88', '873.65', '1.46']
[0 0 0 0 1]


['791105339112.24', '6344.78', '322.12', '952.09', '1.01']
[1 1 1 1 0]


['601303961773.52', '1621.83', '206.71', '859.21', '1.22']
[1 0 0 0 0]


['1233160881181.64', '4977.73', '370.69', '884.60', '1.29']
[1 0 0 0 0]


['1266767853749.22', '4084.02', '375.66', '933.39', '1.28']
[0 0 1 1 1]




In [6]:
my_mesh = load_mesh()
V = load_function_space(my_mesh)
test_domain = np_array([[0.0, 0.1], [0.4, 0.5]])
num_of_spatial_sampling_M = 5
return_as_bool = False
g_constraint = 700
for _ in range(3):
    field_idx = np_random.randint(0, len(data_dir_list_of_fields))
    field_file_path = data_dir_list_of_fields[field_idx]
    sup_dir_of_file = field_file_path[:-len(Path(field_file_path).name)]
    inputs = np_load(f"{sup_dir_of_file}input_data.npy")
    print(inputs[3])
    print(sample_fenics_function(field_file_path=field_file_path,
                                func_space_V=V,
                                mesh=my_mesh,
                                test_domain=test_domain,
                                num_of_spatial_sampling_M=num_of_spatial_sampling_M,
                                return_as_bool=return_as_bool,
                                g_constraint=g_constraint))
    print('\n')

988.9939199539388
[0.03081803 0.46430109]
979.519567247762
[979.51956725 910.2532276  922.58323542 968.36357817 962.90566075]


993.025412044395
[0.06122626 0.41616066]
935.4076597884995
[935.40765979 912.47559025 968.80801719 982.87692437 938.14473544]


871.7764767935669
[0.05633494 0.42475314]
841.6861303912192
[841.68613039 862.9502956  832.41328671 838.88575268 854.77400164]




In [11]:
import numpy as np
from fenics import Point

In [97]:
x_vect = np.random.uniform([test_domain[0,0], test_domain[1,0]], [test_domain[0,1], test_domain[1,1]], size=(num_of_spatial_sampling_M, 2))
# x_vect

In [87]:
my_f = load_fenics_function(data_dir_list_of_fields[0])
a = 0

In [98]:
for x in x_vect:
    print(my_f(Point(x)))

865.254260744931
868.0291106760067
850.3189601987204
796.0808872457875
862.4547035286537


In [99]:
# u = np.zeros(num_of_spatial_sampling_M)
# print(u)
for myx in x_vect:
    print(my_f(myx[0], myx[1]))

865.254260744931
868.0291106760067
850.3189601987204
796.0808872457875
862.4547035286537
